COMPILER=gcc
OUTPUT_FILE=SATSolver.out
CFLAGS=-Wall -fsanitize=address
FILE_SATSOLVER=./src/SATSolver.c
FILE_MASTERADT=./src/masterADT.c
FILE_SLAVE=./src/slave.c
OUTPUT_FILE_SATSOLVER=./src/SATSolver.o
OUTPUT_FILE_MASTERADT=./src/masterADT.o
OUTPUT_FILE_SLAVE=slave.out
all: COMPILE 

COMPILE: $(FILES)
	$(COMPILER) -c $(CFLAGS) -o $(OUTPUT_FILE_SATSOLVER) $(FILE_SATSOLVER)
	$(COMPILER) -c $(CFLAGS) -o $(OUTPUT_FILE_MASTERADT) $(FILE_MASTERADT)
	$(COMPILER) $(CFLAGS) -o $(OUTPUT_FILE_SLAVE) $(FILE_SLAVE)
	$(COMPILER) $(CFLAGS) -o $(OUTPUT_FILE) $(OUTPUT_FILE_SATSOLVER) $(OUTPUT_FILE_MASTERADT)


clean:
	rm -rf $(OUTPUT_FILE) $(OUTPUT_FILE_SATSOLVER) $(OUTPUT_FILE_MASTERADT) $(OUTPUT_FILE_SLAVE)