COMPILER=gcc
EXEC_SATSOLVER=SATSolver.out
EXEC_VIEW=view.out
CFLAGS=-Wall -fsanitize=address
FILE_SATSOLVER=./src/SATSolver.c
FILE_MASTERADT=./src/masterADT.c
FILE_SHMEM_HANDLERADT=./src/shMemHandlerADT.c
FILE_VIEW=./src/view.c
FILE_SLAVE=./src/slave.c
OUTPUT_FILE_SATSOLVER=./src/SATSolver.o
OUTPUT_FILE_MASTERADT=./src/masterADT.o
OUTPUT_FILE_SHMEM_HANDLERADT=./src/shMemHandlerADT.o
OUTPUT_FILE_VIEW=./src/view.o
OUTPUT_FILE_SLAVE=slave.out
all: COMPILE

COMPILE: $(FILES)
	$(COMPILER) -c $(CFLAGS) -o $(OUTPUT_FILE_SATSOLVER) $(FILE_SATSOLVER)
	$(COMPILER) -c $(CFLAGS) -o $(OUTPUT_FILE_MASTERADT) $(FILE_MASTERADT)
	$(COMPILER) -c $(CFLAGS) -o $(OUTPUT_FILE_VIEW) $(FILE_VIEW)
	$(COMPILER) -c $(CFLAGS) -pthread -o $(OUTPUT_FILE_SHMEM_HANDLERADT) $(FILE_SHMEM_HANDLERADT)
	$(COMPILER) $(CFLAGS) -o $(OUTPUT_FILE_SLAVE) $(FILE_SLAVE)
	$(COMPILER) $(CFLAGS) -pthread -o $(EXEC_SATSOLVER) $(OUTPUT_FILE_SATSOLVER) $(OUTPUT_FILE_MASTERADT) $(OUTPUT_FILE_SHMEM_HANDLERADT)
	$(COMPILER) $(CFLAGS) -pthread -o $(EXEC_VIEW) $(OUTPUT_FILE_VIEW) $(OUTPUT_FILE_SHMEM_HANDLERADT)

clean:
	rm -rf $(EXEC_SATSOLVER) $(EXEC_VIEW) $(OUTPUT_FILE_SATSOLVER) $(OUTPUT_FILE_MASTERADT) $(OUTPUT_FILE_SLAVE) $(OUTPUT_FILE_VIEW) $(OUTPUT_FILE_SHMEM_HANDLERADT)

.PHONY: all clean