COMPILER := gcc
CFLAGS := -Wall -g -pthread
OBJECT_SATSOLVER := ./SATSolver.c
OBJECT_MASTERADT := ./masterADT.c
OBJECT_SHMEM_HANDLERADT := ./shMemHandlerADT.c
OBJECT_VIEW := ./view.c
OBJECT_SLAVE := ./slave.c